/* An Entity of a level. */

public abstract class Entity
{
    /// <summary>
    /// Unique ID. The entity's ID is generated by the entity handler
    /// </summary>
    protected int _entityID;

    #region State information
    protected EntityState _currentState;

    public enum EntityState
    {
        active,
        disabled,
    }
    #endregion

    #region Getters and setters
    public EntityState GetState()
    {
        return _currentState;
    }

    public int GetID()
    {
        return _entityID;
    }
    #endregion

    #region On reset
    public abstract void Reset();
    #endregion

    #region Actions and reactions
    public abstract void Update(float deltaTime);
    public abstract void Collide(Entity entity);
    #endregion

    #region Draw
    public abstract void Draw();
    #endregion
}
